name: Deploy Pages

on:
  push:
    branches: [ main ]  # 当 main 分支有 push 时触发

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: github-pages  # 必须有 environment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload .well-known folder
        uses: actions/upload-pages-artifact@v4
        with:
          path: 'docs/.well-known'   # ✅ 只上传 .well-known 文件夹

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
